### ISSUE TITLE
The address has no xudt cells

### ISSUE THREAD

**Issue by fiiph** [scripteric/omiga#3]
```
$ npx ts-node action/transfer.ts
address:  ckb1qyqdjtk4yexsn972x4rdc5nnfv59wvvjl04qq63nha
args_len:  42 66
/ssd/omiga/src/inscription/transfer.ts:5
  serializeWitnessArgs,
                                                         ^
InscriptionXudtException [Error]: The address has no xudt cells
    at /ssd/omiga/src/inscription/transfer.ts:55:11
    at Generator.next (<anonymous>)
    at fulfilled (/ssd/omiga/src/inscription/transfer.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Could you help please? Thanks.

**Comment by scripteric** [comment]
Because you don’t have xudt cell, if you only have ckb transfer, please use npx ts-node  action/transfer-ckb.ts

**Comment by fiiph** [comment]
Thanks! It works.
